spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8

mybatis:
  mapperLocations: classpath:com/rabbiter/am/mapper/*.xml
logging:
  level:
    com.rabbiter.am.dao: debug
server:
  port: 9331
attendance:
  on-time: '08:30'
  off-time: '17:30'
